apiVersion: 1
datasources:
  - name: InfluxDB-Campus
    uid: influx-campus
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: umg
      defaultBucket: campus
    secureJsonData:
      token: $INFLUX_TOKEN
