# Mosquitto — broker MQTT del Campus (Data Center, VLAN 50: SRV-SERVICIOS 10.10.4.2 en el diseño)

listener 1883
protocol mqtt

listener 9001
protocol websockets

# Seguridad: sin acceso anónimo, usuarios con contraseña y ACL por tópico
allow_anonymous false
password_file /mosquitto/data/passwd
# El ACL se copia a /mosquitto/data al arrancar para darle permisos 0600 (ver docker-compose.yml)
acl_file /mosquitto/data/acl

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp_format %Y-%m-%dT%H:%M:%S

# Archivos adicionales (p. ej. el bridge para Wokwi)
include_dir /mosquitto/config/conf.d
